apiVersion: v1
kind: Namespace
metadata:
  name: homelab
  labels:
    app.kubernetes.io/part-of: pi-k3s-lab
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.36
